# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = CaesarGUI
DESTDIR = ../x64/Debug
CONFIG += debug app
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
FORMS += sortdialog.ui
include(CaesarGUI.pri)
